SET DATABASE SQL SYNTAX MYS TRUE;

CREATE TABLE IF NOT EXISTS UPLOAD_PROGRESS (
    PAGE_ID         VARCHAR(16)     NOT NULL,
    USERNAME        VARCHAR(64)     NOT NULL,
    COLUMN_NAME     VARCHAR(32),
    UPLOAD_STATUS   VARCHAR(16)     NOT NULL,
    
    PRIMARY KEY (PAGE_ID, USERNAME)
);

CREATE TABLE IF NOT EXISTS USERS (
	USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(50) NOT NULL,
	ENABLED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
	USERNAME VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);

CREATE TABLE IF NOT EXISTS GROUPS (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GROUP_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS GROUP_AUTHORITIES (
	GROUP_ID BIGINT NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID)
);

CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	GROUP_ID BIGINT NOT NULL,
	FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID)
);
