SET DATABASE SQL SYNTAX MYS TRUE;

CREATE TABLE IF NOT EXISTS UPLOAD_PROGRESS (
    PAGE_ID         VARCHAR(16)     NOT NULL,
    USERNAME        VARCHAR(64)     NOT NULL,
    COLUMN_NAME     VARCHAR(32),
    UPLOAD_STATUS   VARCHAR(16)     NOT NULL,
    
    PRIMARY KEY (PAGE_ID, USERNAME)
);