SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE "MBRT_MBR_ID_MST" ( 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"OCBCOM_LGN_ID" VARCHAR2(100 BYTE), 
	"CI_NO" VARCHAR2(88 BYTE), 
	"CARD_NO" VARCHAR2(88 BYTE), 
	"SYW_MBR_ID" VARCHAR2(100 BYTE), 
	"EVS_MBR_ID" VARCHAR2(100 BYTE), 
	"MBR_KOR_NM" VARCHAR2(100 BYTE), 
	"LD_DTTM" VARCHAR2(14 BYTE), 
	"MART_UPD_DTTM" VARCHAR2(14 BYTE)
);

CREATE TABLE IF NOT EXISTS "DW_MBR_MST" ( 
	"MBRSHP_PGM_ID" VARCHAR2(1 BYTE), 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"MBR_FG_CD" VARCHAR2(1 BYTE), 
	"MBR_KOR_NM" VARCHAR2(100 BYTE), 
	"MBR_ENG_NM" VARCHAR2(100 BYTE), 
	"MBR_STS_CD" VARCHAR2(1 BYTE), 
	"HOME_TEL_NO" VARCHAR2(13 BYTE), 
	"ORIHOME_ZIPCD" VARCHAR2(7 BYTE), 
	"ORIHOME_BASIC_ADDR" VARCHAR2(300 BYTE), 
	"ORIHOME_DTL_ADDR" VARCHAR2(300 BYTE), 
	"HOME_ZIPCD" VARCHAR2(6 BYTE), 
	"HOME_BASIC_ADDR" VARCHAR2(300 BYTE), 
	"HOME_DTL_ADDR" VARCHAR2(300 BYTE), 
	"ROAD_NM_HOME_ZIPCD" VARCHAR2(6 BYTE), 
	"ROAD_HOME_BASIC_ADDR" VARCHAR2(300 BYTE), 
	"ROAD_HOME_DTL_ADDR" VARCHAR2(300 BYTE), 
	"HOME_HJD_SGRP_CD" VARCHAR2(8 BYTE), 
	"HOME_BJD_SGRP_CD" VARCHAR2(10 BYTE), 
	"HOME_ADDR_RSLT_CD" VARCHAR2(6 BYTE), 
	"HOME_ROAD_ADDR_RSLT_CD" VARCHAR2(6 BYTE), 
	"HOME_APT_RSLT_CD" VARCHAR2(3 BYTE), 
	"JOBP_TEL_NO" VARCHAR2(13 BYTE), 
	"JOBP_ETSN_NO" VARCHAR2(4 BYTE), 
	"ORIJOBP_ZIPCD" VARCHAR2(7 BYTE), 
	"ORIJOBP_BASIC_ADDR" VARCHAR2(300 BYTE), 
	"ORIJOBP_DTL_ADDR" VARCHAR2(300 BYTE), 
	"JOBP_ZIPCD" VARCHAR2(6 BYTE), 
	"JOBP_BASIC_ADDR" VARCHAR2(300 BYTE), 
	"JOBP_DTL_ADDR" VARCHAR2(300 BYTE), 
	"ROAD_NM_JOBP_ZIPCD" VARCHAR2(6 BYTE), 
	"ROAD_JOBP_BASIC_ADDR" VARCHAR2(300 BYTE), 
	"ROAD_JOBP_DTL_ADDR" VARCHAR2(300 BYTE), 
	"JOBP_HJD_SGRP_CD" VARCHAR2(8 BYTE), 
	"JOBP_BJD_SGRP_CD" VARCHAR2(10 BYTE), 
	"JOBP_ADDR_RSLT_CD" VARCHAR2(6 BYTE), 
	"JOBP_ROAD_ADDR_RSLT_CD" VARCHAR2(6 BYTE), 
	"JOBP_APT_RSLT_CD" VARCHAR2(3 BYTE), 
	"CLPHN_SVC_CD" VARCHAR2(3 BYTE), 
	"CLPHN_NO" VARCHAR2(16 BYTE), 
	"EMAIL_ADDR" VARCHAR2(200 BYTE), 
	"HOME_TEL_CORCT_FG_CD" VARCHAR2(1 BYTE), 
	"JOBP_TEL_CORCT_FG_CD" VARCHAR2(1 BYTE), 
	"CLPHN_CORCT_FG_CD" VARCHAR2(1 BYTE), 
	"HOME_TEL_LENGTH_CORCT_YN" VARCHAR2(1 BYTE), 
	"JOBP_TEL_LENGTH_CORCT_YN" VARCHAR2(1 BYTE), 
	"CLPHN_LENGTH_CORCT_YN" VARCHAR2(1 BYTE), 
	"HOME_ADDR_CORCT_FG_CD" VARCHAR2(1 BYTE), 
	"JOBP_ADDR_CORCT_FG_CD" VARCHAR2(1 BYTE), 
	"REG_DTTM" DATE, 
	"UPD_DTTM" DATE, 
	"EXTRCT_DT" VARCHAR2(8 BYTE), 
	"LD_DTTM" DATE, 
	"DW_UPD_DTTM" DATE
);

CREATE TABLE IF NOT EXISTS "DW_MBR_UPD_HST" ( 
	"MBRSHP_PGM_ID" VARCHAR2(1 BYTE), 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"MBR_UPD_ITM_CD" VARCHAR2(4 BYTE), 
	"UPD_DT" VARCHAR2(8 BYTE), 
	"UPD_TM" VARCHAR2(6 BYTE), 
	"UPD_PREV_DATA" VARCHAR2(300 BYTE), 
	"UPD_AF_DATA" VARCHAR2(300 BYTE), 
	"INFL_CHNL_CD" VARCHAR2(10 BYTE), 
	"REGR_ID" VARCHAR2(8 BYTE), 
	"REG_DTTM" DATE, 
	"UPDR_ID" VARCHAR2(8 BYTE), 
	"UPD_DTTM" DATE, 
	"EXTRCT_DT" VARCHAR2(8 BYTE), 
	"LD_DTTM" DATE, 
	"DW_UPD_DTTM" DATE
);

CREATE TABLE IF NOT EXISTS "DW_MBR_CI_INFO" ( 
	"MBRSHP_PGM_ID" VARCHAR2(1 BYTE), 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"CI_NO" VARCHAR2(88 BYTE), 
	"INDIV_IDNTF_REF_NO" VARCHAR2(10 BYTE), 
	"IPIN_DUP_CHK_NO" VARCHAR2(64 BYTE), 
	"SPPSTN_RNO_TP_CD" VARCHAR2(2 BYTE), 
	"REGR_ID" VARCHAR2(8 BYTE), 
	"REG_DTTM" DATE, 
	"UPDR_ID" VARCHAR2(8 BYTE), 
	"UPD_DTTM" DATE, 
	"EXTRCT_DT" VARCHAR2(8 BYTE), 
	"LD_DTTM" DATE, 
	"DW_UPD_DTTM" DATE
);

CREATE TABLE IF NOT EXISTS "MART_MBR_INQ_INFO" ( 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"CUST_ID" VARCHAR2(11 BYTE), 
	"PNT_EXTNCT_YN" VARCHAR2(1 BYTE), 
	"LEGL_BTHDT" VARCHAR2(8 BYTE), 
	"LEGL_GNDR_FG_CD" VARCHAR2(1 BYTE), 
	"FST_CARD_RREG_DT" VARCHAR2(8 BYTE), 
	"DESTR_EXPCTN_DT" VARCHAR2(8 BYTE), 
	"FNL_ERNG_DT" VARCHAR2(8 BYTE), 
	"FNL_CARD_RREG_DT" VARCHAR2(8 BYTE), 
	"FNL_CNSOF_ENQ_DT" VARCHAR2(8 BYTE), 
	"FNL_PRD_PCHS_DT" VARCHAR2(8 BYTE), 
	"FNL_PNT_INQ_DT" VARCHAR2(8 BYTE), 
	"LD_DTTM" DATE, 
	"MART_UPD_DTTM" DATE
);

CREATE TABLE IF NOT EXISTS "MART_CLPHN_NO_DUP_INFO" ( 
	"CLPHN_NO" VARCHAR2(16 BYTE), 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"LD_DTTM" DATE, 
	"MART_UPD_DTTM" DATE
);

CREATE TABLE IF NOT EXISTS "MART_EMAIL_ADDR_DUP_INFO" ( 
	"EMAIL_ADDR" VARCHAR2(200 BYTE), 
	"MBR_ID" VARCHAR2(9 BYTE), 
	"LD_DTTM" DATE, 
	"MART_UPD_DTTM" DATE
);

CREATE TABLE IF NOT EXISTS "DW_OCB_INTG_CD" ( 
	"DOMN_ID" VARCHAR2(50 BYTE), 
	"DTL_CD" VARCHAR2(50 BYTE), 
	"APPL_END_DT" VARCHAR2(8 BYTE), 
	"APPL_START_DT" VARCHAR2(8 BYTE), 
	"DOMN_KOR_NM" VARCHAR2(200 BYTE), 
	"DOMN_ENG_NM" VARCHAR2(50 BYTE), 
	"DTL_CD_NM" VARCHAR2(200 BYTE), 
	"DTL_CD_DESC" VARCHAR2(400 BYTE), 
	"HRNK_DOMN_ID" VARCHAR2(50 BYTE), 
	"HRNK_DTL_CD" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(300 BYTE), 
	"REG_DTTM" VARCHAR2(14 BYTE), 
	"DW_UPD_DTTM" VARCHAR2(14 BYTE), 
	"IND_CD" VARCHAR2(1 BYTE)
);

