create table MOCK_TB_SEL_TRX_HIST (
	rcv_dt DATE,
	rcv_seq VARCHAR(50),
	appr_dttm DATE,
	rep_appr_no VARCHAR(50),
	appr_no VARCHAR(50),
	sale_dttm DATE,
	mbr_id VARCHAR(50),
	card_dtl_grp VARCHAR(50),
	card_no VARCHAR(50),
	alcmpn VARCHAR(50),
	mcnt VARCHAR(50),
	stlmt_mcnt VARCHAR(50),
	pnt_knd VARCHAR(50),
	slip VARCHAR(50),
	sale_amt INT,
	pnt INT,
	cs_mbr_cmmsn INT,
	cmmsn INT,
	pmnt_way VARCHAR(50),
	org VARCHAR(50),
	oil_prdct_sgrp VARCHAR(50),
	sale_qty INT,
	cpn_prd VARCHAR(20),
	trx_type VARCHAR(50)
);
