SET DATABASE SQL SYNTAX MYS TRUE;

CREATE TABLE UPLOAD_PROGRESS (
    PAGE_ID         VARCHAR(16)     NOT NULL,
    USERNAME        VARCHAR(64)     NOT NULL,
    COLUMN_NAME     VARCHAR(32),
    FILENAME		VARCHAR(256),
    UPLOAD_STATUS   VARCHAR(16)     NOT NULL,
    
    PRIMARY KEY (PAGE_ID, USERNAME)
);

CREATE TABLE USERS (
	USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(50),
	ENABLED BOOLEAN NOT NULL,
	PTS_USERNAME VARCHAR(50),
	BEGIN_DTTM VARCHAR(14),
	END_DTTM VARCHAR(14)
);

CREATE TABLE AUTHORITIES (
	USERNAME VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,

	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY);

CREATE TABLE PAGE_ACCESS (
	USERNAME VARCHAR(50) NOT NULL,
	PAGE_ID VARCHAR(16) NOT NULL,

	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_PAGE_USERNAME ON PAGE_ACCESS (USERNAME, PAGE_ID);
