SET DATABASE SQL SYNTAX MYS TRUE;

CREATE TABLE IF NOT EXISTS USERS (
	USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(50),
	ENABLED BOOLEAN NOT NULL,
	PTS_USERNAME VARCHAR(50),
	BEGIN_DTTM VARCHAR(14),
	END_DTTM VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
	USERNAME VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,

	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY);

CREATE TABLE IF NOT EXISTS PAGE_ACCESS (
	USERNAME VARCHAR(50) NOT NULL,
	PAGE_ID VARCHAR(16) NOT NULL,

	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_PAGE_USERNAME ON PAGE_ACCESS (USERNAME, PAGE_ID);

CREATE TABLE IF NOT EXISTS UPLOAD_PROGRESS (
    USERNAME VARCHAR(50) NOT NULL,
    PAGE_ID VARCHAR(16) NOT NULL,
    COLUMN_NAME VARCHAR(32),
    FILENAME VARCHAR(256),
    UPLOAD_STATUS VARCHAR(16) NOT NULL,
    
    PRIMARY KEY(USERNAME, PAGE_ID),
    FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE IF NOT EXISTS IDMS_LOGINOUT (
	USERNAME VARCHAR(50) NOT NULL,
	USER_IP VARCHAR(15) NOT NULL,
	LOGIN_DTTM VARCHAR(14) NOT NULL,
	LOGOUT_DTTM VARCHAR(14)
);
CREATE UNIQUE INDEX IX_USER_IP_DTTM_USERNAME ON IDMS_LOGINOUT(USERNAME, USER_IP, LOGIN_DTTM);
